### ISSUE TITLE
echart : à rendre robuste quelque soit le nombre de pays selectionnés

### ISSUE THREAD

**Issue by brunolajoie** [brunolajoie/electricitymap-pro#34]
1/ 1 couleur par pays dans le line chart.

2/ la légende doit pas merder quand on a bcp de pays selectionnés!

**Comment by corradio** [comment]
Pour 2/, je propose de juste désactiver le graph quand il y a plus de 10 pays. What do you think?

**Comment by brunolajoie** [comment]
Yes, on va gérer ca conditionellement, bonne idée.

**Comment by brunolajoie** [comment]
@corradio ,si tu as un petit moment pour améliorer le layout à l'intérieur du canvas echart dans _echarts_carbon_time_serie.html.erb , ca pourrait m'etre utile. no pb sinon, je verrais si j'ai le temps later. cheers
